apiVersion: v1
kind: Secret
metadata:
  name: medusa-secrets
  namespace: medusa
type: Opaque
stringData:
  POSTGRES_USER: 
  POSTGRES_PASSWORD: 
  POSTGRES_DB: 
  JWT_SECRET: 
  COOKIE_SECRET: 
  DATABASE_URL: